100.learn-more-about-oceanbase=OceanBaseの紹介
  400.compatibility-with-oracle=Oracleとの互換性比較
200.quickstart=クイックスタート
  200.get-started-with-oceanbase-sql=OceanBase SQLを始める
  300.create-sample-application-of-mysql-mode=MySQLモードでのサンプルアプリケーション作成
  300.create-sample-application-of-oracle-mode=Oracleモードでのサンプルアプリケーション作成
  500.experience-advanced-features-of-oceanbase=OceanBaseの高度な機能の体験
    100.experience-scalable-oltp=Scalable OLTPの体験
300.develop=アプリケーション開発
  100.application-development-of-mysql-mode=MySQLモードによるアプリケーション開発
    100.connect-to-oceanbase-database-of-mysql-mode=OceanBaseデータベースへの接続
      1400.use-the-database-connection-pool-of-mysql-mode=データベース接続プールの使用
    200.sample-program-of-mysql-mode=サンプルプログラム
      100.java-of-mysql-mode=Java
      200.python-of-mysql-mode=Python
      300.c-of-mysql-mode=C
      400.go-of-mysql-mode=Go
      500.php-of-mysql-mode=PHP
      600.rust-of-mysql-mode=Rust
      700.ruby-of-mysql-mode=Ruby
    300.database-object-planning-of-mysql-mode=データベースオブジェクト設計
    400.write-data-of-mysql-mode=データ書き込み
    500.read-data-of-mysql-mode=データ読み込み
      200.multi-table-join-query-of-mysql-mode=テーブル結合クエリ
      300.use-operators-and-functions-in-query-of-mysql-mode=クエリ内での演算子と関数の使用
    600.transaction-in-develop-of-mysql-mode=トランザクション
      300.transaction-savepoints-of-mysql-mode=セーブポイント
    700.application-error-handling-specification-and-common-error-solutions=アプリケーションエラーハンドリング仕様と一般的なエラー解決策
      100.application-error-handling-specification-of-mysql-mode=アプリケーションエラーハンドリング仕様
  200.application-development-of-oracle-mode=Oracleモードによるアプリケーション開発
    100.connect-to-oceanbase-database-of-oracle-mode=OceanBaseデータベースへの接続
      1300.use-the-database-connection-pool-of-oracle-mode=データベース接続プールの使用
    200.sample-program-of-oracle-mode=サンプルプログラム
      100.java-of-oracle-mode=Java
      300.c-of-oracle-mode=C/C++
    300.database-object-planning-of-oracle-mode=データベースオブジェクト設計
    400.write-data-of-oracle-mode=データ書き込み
    500.read-data-of-oracle-mode=データ読み込み
      200.multi-table-join-query-of-oracle-mode=テーブル結合クエリ
      300.use-operators-and-functions-in-query-of-oracle-mode=クエリ内での演算子と関数の使用
    600.transaction-in-develop-of-oracle-mode=トランザクション
      300.transaction-savepoints-of-oracle-mode=セーブポイント
    700.application-error-handling-specification-and-common-error-solutions-of-oracle-mode=アプリケーションエラーハンドリング仕様と一般的なエラー解決策
      100.application-error-handling-specification-of-oracle-mode=アプリケーションエラーハンドリング仕様
400.deploy=データベースのデプロイ
  300.deploy-oceanbase-enterprise-edition=OceanBase Enterprise Editionのデプロイ
    200.preparations-before-deploy=デプロイ前の準備
    300.deploy-through-a-graphical-interface=グラフィカルユーザーインターフェースを使用したデプロイ
      100.configuring-the-deploy-environment-through-oat=OATでのデプロイ環境の設定
      200.deploy-ocp-use-oat=OCPのデプロイ
      300.deploy-oceanbase-cluster-use-ocp=OCPを使用したOceanBaseクラスタのデプロイ
    400.deploy-through-the-command-line=コマンドラインを使用したデプロイ
      100.configure-a-deployment-environment-command-line=oatcliでのデプロイ環境の設定
      200.deploy-the-oceanbase-cluster-command-line=コマンドラインを使用したOceanBaseクラスタのデプロイ
  500.deploy-oceanbase-database-community-edition=OceanBase Community Edition のデプロイ
    200.local-deployment=ローカルデプロイ
      200.environment-and-configuration-checks=デプロイ前の設定
      400.deploy-by-ui=グラフィカルユーザーインターフェースを使用したデプロイ
620.obap=OceanBase AP
  150.obap-deploy=デプロイ紹介
  200.obap-data-design=データテーブル設計
    100.data-design-best-practice=ベストプラクティス
  300.obap-data-collection=データ収集
    300.obap-import-data=データのインポート
      20.bypass-import=ダイレクトロード
  350.data-processing=データ加工
  500.obap-query=クエリ加速
  700.performance-tuning=パフォーマンスの診断およびチューニング
640.ob-vector-search=ベクトル検索
  100.ob-vector-search-overview=ベクトル検索の概要
  120.ob-vector-search-quick-start=ベクトル検索のクイックスタート
  600.ob-vector-search-integration=AI統合
  700.ob-vector-search-reference=ベクトル検索の参考
    900.ob-vector-search-supported-clients-and-languages=クライアントとプログラミング言語
680.ecological-integration=エコシステム統合
  200.orms-frameworks=ORMフレームワーク
    100.java=Java
    300.go=Go
    800.php=PHP
  300.schema-evolution=データベースのバージョン管理
  400.data-ingestion=データ統合
  500.sql-development=SQL開発
  600.orchestration=編成とスケジューリング
  700.visualization=可視化ツール
  1000.management=データベース管理
  1100.AI=AI
690.practical-tutorial=実践チュートリアル